---------------- Starting Your Algo --------------------
/home/d/duong/terminal-agent/rl-algo2/rl_strategy.py:288: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(defence_actions), np.array(attack_actions)
2021-11-02 19:34:57.320566: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2021-11-02 19:34:57.329910: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2299990000 Hz
2021-11-02 19:34:57.334013: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5583ee545f10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-11-02 19:34:57.334074: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-11-02 19:34:57.334221: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Performing turn 0 of your custom algo strategy
action choosen: 0, epsilon: 0.01
action choosen: 183, epsilon: 0.01
Could not upgrade a unit from [21, 12]. Location has no structures or is enemy territory.
action choosen: 83, epsilon: 0.01
action choosen: 33, epsilon: 0.01
action choosen: 77, epsilon: 0.01
action choosen: 8, epsilon: 0.01
action choosen: 3, epsilon: 0.01
action choosen: 28, epsilon: 0.01
action choosen: 62, epsilon: 0.01
action choosen: 44, epsilon: 0.01
action choosen: 81, epsilon: 0.01
Could not spawn PI at location [14, 0]. Not enough resources.
action choosen: 54, epsilon: 0.01
action choosen: 44, epsilon: 0.01
Could not spawn SI at location [7, 6]. Not enough resources.
action choosen: 53, epsilon: 0.01
Could not spawn EF at location [24, 13]. Location is blocked.
action choosen: 4, epsilon: 0.01
Could not spawn EI at location [27, 13]. Not enough resources.
action choosen: 15, epsilon: 0.01
Could not upgrade a unit from [26, 13]. Location has no structures or is enemy territory.
action choosen: 18, epsilon: 0.01
Could not spawn PI at location [3, 10]. Not enough resources.
action choosen: 76, epsilon: 0.01
Traceback (most recent call last):
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2328, in get_attr
    pywrap_tf_session.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'args_1' has no attr named '_read_only_resource_inputs'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/d/duong/terminal-agent/rl-algo2/rl_strategy.py", line 417, in <module>
    algo.start()
  File "/home/d/duong/terminal-agent/rl-algo2/gamelib/algocore.py", line 79, in start
    self.on_turn(game_state_string)
  File "/home/d/duong/terminal-agent/rl-algo2/rl_strategy.py", line 156, in on_turn
    attack_action_index = self.attack_agent.choose_action(next_s, i)
  File "/home/d/duong/terminal-agent/rl-algo2/rl_agent.py", line 175, in choose_action
    actions = self.dqn.predict(state)[0]
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 88, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1240, in predict
    data_handler = data_adapter.DataHandler(
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1100, in __init__
    self._adapter = adapter_cls(
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 364, in __init__
    dataset = self.slice_inputs(indices_dataset, inputs)
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 396, in slice_inputs
    dataset = dataset.map(
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1623, in map
    return ParallelMapDataset(
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4016, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3221, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2531, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2496, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2657, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1022, in func_graph_from_py_func
    func_graph.variables = variables
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/framework/auto_control_deps.py", line 354, in __exit__
    for inp, resource_type in _get_resource_inputs(op):
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/framework/auto_control_deps.py", line 454, in _get_resource_inputs
    reads, writes = utils.get_read_write_resource_inputs(op)
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/framework/auto_control_deps_utils.py", line 106, in get_read_write_resource_inputs
    read_only_input_indices = op.get_attr(READ_ONLY_RESOURCE_INPUTS_ATTR)
  File "/home/d/duong/anaconda3/envs/terminal-agent/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2330, in get_attr
    except errors.InvalidArgumentError as e:
KeyboardInterrupt
